"""empty message

Revision ID: de0d0f31ae1d
Revises: 
Create Date: 2026-07-30 00:18:25.823612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0d0f31ae1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'group_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['muscle_group.group_name'], name='fk_equipment_muscle_group'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_equipment_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_name', 'user_id', name='uq_equipment')
    )
    op.create_index('idx_equipment_name', 'equipment', ['equipment_name'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_exercise_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('muscle_name', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_name'], ['muscle_group.group_name'], name='fk_muscle_muscle_group'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_muscle_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muscle_name', 'group_name', name='uq_muscle')
    )
    op.create_table('workout_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_name', sa.String(), nullable=False),
    sa.Column('workout_plan_goal', sa.String(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_workout_plan_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_plan_name', 'user_id', name='uq_workout_plan')
    )
    op.create_table('exercise_equipment',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='fk_exercise_equipment_equipment'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_exercise_equipment_exercise'),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    op.create_table('exercise_muscle',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_exercise_muscle_exercise'),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscle.id'], name='fk_exercise_muscle_muscle'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscle_id')
    )
    op.create_table('workout_split',
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], name='fk_workout_split_workout_plan'),
    sa.PrimaryKeyConstraint('split', 'workout_plan_id')
    )
    op.create_table('split_exercise',
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('rest_time', sa.Integer(), nullable=True),
    sa.Column('advanced_technique', sa.String(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_split_exercise_exercise'),
    sa.ForeignKeyConstraint(['split', 'workout_plan_id'], ['workout_split.split', 'workout_split.workout_plan_id'], name='fk_split_exercise_workout_split'),
    sa.PrimaryKeyConstraint('workout_plan_id', 'split', 'exercise_id', 'execution_order')
    )
    op.create_table('workout_report',
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['split', 'workout_plan_id'], ['workout_split.split', 'workout_split.workout_plan_id'], name='fk_workout_report_workout_plan'),
    sa.PrimaryKeyConstraint('report_date', 'id', 'workout_plan_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('split_set_report',
    sa.Column('workout_report_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name='fk_set_report_exercise'),
    sa.ForeignKeyConstraint(['workout_report_id'], ['workout_report.id'], name='fk_set_report_workout_report'),
    sa.PrimaryKeyConstraint('workout_report_id', 'exercise_id', 'split', 'set_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_set_report')
    op.drop_table('workout_report')
    op.drop_table('split_exercise')
    op.drop_table('workout_split')
    op.drop_table('exercise_muscle')
    op.drop_table('exercise_equipment')
    op.drop_table('workout_plan')
    op.drop_table('muscle')
    op.drop_table('exercise')
    op.drop_index('idx_equipment_name', table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('user')
    op.drop_table('muscle_group')
    # ### end Alembic commands ###
