CREATE TABLE "usuario" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "username" VARCHAR(40) NOT NULL,
  "email" VARCHAR(100) NOT NULL,
  "nome" VARCHAR(100) NOT NULL,
  "password" VARCHAR(512) NOT NULL,
  PRIMARY KEY ("id_usuario")
);

CREATE TABLE "grupamento" (
  "nome_grupamento" VARCHAR(50) NOT NULL,
  "id_usuario" INTEGER,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("nome_grupamento")
);

CREATE TABLE "aparelho" (
  "id_aparelho" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "id_usuario" INTEGER,
  "nome_grupamento" VARCHAR(50) NOT NULL,
  "nome_aparelho" VARCHAR(50) NOT NULL,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("id_aparelho")
);

CREATE TABLE "musculo" (
  "id_musculo" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "nome_grupamento" VARCHAR(50) NOT NULL,
  "id_usuario" INTEGER,
  "nome_musculo" VARCHAR(50) NOT NULL,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("id_musculo")
);

CREATE TABLE "exercicio" (
  "id_exercicio" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "id_usuario" INTEGER,
  "nome_exercicio" VARCHAR(50) NOT NULL,
  "descricao" VARCHAR(120),
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("id_exercicio")
);

CREATE TABLE "exercicio_musculo" (
  "id_musculo" INTEGER,
  "id_exercicio" INTEGER
);

CREATE TABLE "exercicio_aparelho" (
  "id_aparelho" INTEGER,
  "id_exercicio" INTEGER
);

CREATE TABLE "ficha_treino" (
  "id_ficha_treino" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "id_usuario" INTEGER NOT NULL,
  "nome_ficha_treino" VARCHAR(20) NOT NULL,
  "objetivo_ficha_treino" VARCHAR(50) NOT NULL,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("id_ficha_treino")
);

CREATE TABLE "divisao_treino" (
  "divisao" VARCHAR(20) NOT NULL,
  "id_ficha_treino" INTEGER NOT NULL,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("divisao", "id_ficha_treino")
);

CREATE TABLE "relatorio_treino" (
  "id_relatorio_treino" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "id_ficha_treino" INTEGER NOT NULL,
  "data_relatorio" DATE NOT NULL,
  "divisao" VARCHAR(20) NOT NULL,
  PRIMARY KEY ("id_relatorio_treino")
);

CREATE TABLE "divisao_exercicio" (
  "id_ficha_treino" INTEGER NOT NULL,
  "divisao" VARCHAR(20) NOT NULL,
  "id_exercicio" INTEGER NOT NULL,
  "ordem_execucao" INTEGER NOT NULL,
  "series" INTEGER NOT NULL,
  "repeticoes" VARCHAR(10) NOT NULL,
  "tecnica_avancada" VARCHAR(30),
  "descanso" INTEGER NOT NULL,
  "ativo" BOOLEAN DEFAULT true,
  PRIMARY KEY ("id_ficha_treino", "divisao", "id_exercicio", "ordem_execucao")
);

CREATE TABLE "serie_relatorio" (
  "id_relatorio_treino" INTEGER NOT NULL,
  "id_exercicio" INTEGER NOT NULL,
  "divisao" VARCHAR(20) NOT NULL,
  "id_ficha_treino" INTEGER NOT NULL,
  "ordem_execucao" INTEGER NOT NULL,
  "numero_serie" INTEGER NOT NULL,
  "repeticoes" VARCHAR(20) NOT NULL,
  "carga" INTEGER NOT NULL,
  "observacao" VARCHAR(255),
  PRIMARY KEY ("id_relatorio_treino", "id_exercicio", "divisao", "id_ficha_treino", "numero_serie")
);

CREATE UNIQUE INDEX "uq_usuario_email" ON "usuario" ("email");

CREATE INDEX "id_username_usuario" ON "usuario" ("username");

CREATE INDEX "id_email_usuario" ON "usuario" ("email");

CREATE UNIQUE INDEX "uq_grupamento" ON "grupamento" ("id_usuario", "nome_grupamento");

CREATE INDEX "idx_grupamento_id_usuario" ON "grupamento" ("id_usuario");

CREATE UNIQUE INDEX "uq_aparelho" ON "aparelho" ("id_usuario", "nome_grupamento", "nome_aparelho");

CREATE INDEX "idx_id_usuario_nome_grupamento_aparelho" ON "aparelho" ("id_usuario", "nome_grupamento");

CREATE UNIQUE INDEX "uq_musculo" ON "musculo" ("id_usuario", "nome_grupamento", "nome_musculo");

CREATE INDEX "idx_id_usuario_nome_grupamento_musculo" ON "musculo" ("id_usuario", "nome_grupamento");

CREATE UNIQUE INDEX "uq_exercicio" ON "exercicio" ("id_usuario", "nome_exercicio");

CREATE INDEX "idx_id_exercicio_exercicio" ON "exercicio" ("id_exercicio");

CREATE INDEX "idx_id_exercicio_exercicio_musculo" ON "exercicio_musculo" ("id_exercicio");

CREATE INDEX "idx_id_musculo_exercicio_musculo" ON "exercicio_musculo" ("id_musculo");

CREATE INDEX "idx_id_aparelho_exercicio_aparelho" ON "exercicio_aparelho" ("id_aparelho");

CREATE INDEX "idx_id_exercicio_exercicio_aparelho" ON "exercicio_aparelho" ("id_exercicio");

CREATE UNIQUE INDEX "uq_ficha_treino" ON "ficha_treino" ("id_usuario", "nome_ficha_treino");

CREATE INDEX "idx_id_usuario_ficha_treino" ON "ficha_treino" ("id_usuario");

CREATE INDEX "idx_id_ficha_treino_divisao_exercicio" ON "divisao_exercicio" ("id_ficha_treino");

CREATE INDEX "idx_id_ficha_treino_id_relatorio_treino_serie_relatorio" ON "serie_relatorio" ("id_ficha_treino", "id_relatorio_treino");

ALTER TABLE "grupamento" ADD CONSTRAINT "fk_grupamento_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "aparelho" ADD CONSTRAINT "fk_aparelho_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "aparelho" ADD CONSTRAINT "fk_aparelho_grupamento" FOREIGN KEY ("nome_grupamento") REFERENCES "grupamento" ("nome_grupamento");

ALTER TABLE "musculo" ADD CONSTRAINT "fk_musculo_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "musculo" ADD CONSTRAINT "fk_musculo_grupamento" FOREIGN KEY ("nome_grupamento") REFERENCES "grupamento" ("nome_grupamento");

ALTER TABLE "exercicio" ADD CONSTRAINT "fk_exercicio_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "exercicio_musculo" ADD CONSTRAINT "fk_exercicio_musculo_musculo" FOREIGN KEY ("id_musculo") REFERENCES "musculo" ("id_musculo");

ALTER TABLE "exercicio_musculo" ADD CONSTRAINT "fk_exercicio_musculo_exercicio" FOREIGN KEY ("id_exercicio") REFERENCES "exercicio" ("id_exercicio");

ALTER TABLE "exercicio_aparelho" ADD CONSTRAINT "fk_exercicio_aparelho_aparelho" FOREIGN KEY ("id_aparelho") REFERENCES "aparelho" ("id_aparelho");

ALTER TABLE "exercicio_aparelho" ADD CONSTRAINT "fk_exercicio_aparelho_exercicio" FOREIGN KEY ("id_exercicio") REFERENCES "exercicio" ("id_exercicio");

ALTER TABLE "ficha_treino" ADD CONSTRAINT "fk_ficha_treino_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "divisao_treino" ADD CONSTRAINT "fk_divisao_treino_ficha_treino" FOREIGN KEY ("id_ficha_treino") REFERENCES "ficha_treino" ("id_ficha_treino");

ALTER TABLE "relatorio_treino" ADD CONSTRAINT "fk_relatorio_treino_divisao_treino" FOREIGN KEY ("id_ficha_treino", "divisao") REFERENCES "divisao_treino" ("id_ficha_treino", "divisao");

ALTER TABLE "divisao_exercicio" ADD CONSTRAINT "fk_divisao_exercicio_divisao_treino" FOREIGN KEY ("id_ficha_treino", "divisao") REFERENCES "divisao_treino" ("id_ficha_treino", "divisao");

ALTER TABLE "divisao_exercicio" ADD CONSTRAINT "fk_divisao_exercicio_exercicio" FOREIGN KEY ("id_exercicio") REFERENCES "exercicio" ("id_exercicio");

ALTER TABLE "serie_relatorio" ADD CONSTRAINT "fk_serie_relatorio_divisao_exercicio" FOREIGN KEY ("id_ficha_treino", "divisao", "id_exercicio", "ordem_execucao") REFERENCES "divisao_exercicio" ("id_ficha_treino", "divisao", "id_exercicio", "ordem_execucao");

ALTER TABLE "serie_relatorio" ADD CONSTRAINT "fk_serie_relatorio_relatorio_treino" FOREIGN KEY ("id_relatorio_treino") REFERENCES "relatorio_treino" ("id_relatorio_treino");
