CREATE TABLE "user" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "email" VARCHAR(100) NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "password" VARCHAR(512) NOT NULL,
  PRIMARY KEY ("user_id")
);

CREATE TABLE "muscle_group" (
  "group_name" VARCHAR(50) NOT NULL,
  "user_id" INTEGER,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("group_name")
);

CREATE TABLE "equipment" (
  "equipment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER,
  "group_name" VARCHAR(50) NOT NULL,
  "equipment_name" VARCHAR(50) NOT NULL,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("equipment_id")
);

CREATE TABLE "muscle" (
  "muscle_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "group_name" VARCHAR(50) NOT NULL,
  "user_id" INTEGER,
  "muscle_name" VARCHAR(50) NOT NULL,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("muscle_id")
);

CREATE TABLE "exercise" (
  "exercise_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER,
  "exercise_name" VARCHAR(50) NOT NULL,
  "description" VARCHAR(120),
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("exercise_id")
);

CREATE TABLE "exercise_muscle" (
  "muscle_id" INTEGER,
  "exercise_id" INTEGER
);

CREATE TABLE "exercise_equipment" (
  "equipment_id" INTEGER,
  "exercise_id" INTEGER
);

CREATE TABLE "workout_plan" (
  "workout_plan_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INTEGER NOT NULL,
  "workout_plan_name" VARCHAR(20) NOT NULL,
  "workout_plan_goal" VARCHAR(50) NOT NULL,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("workout_plan_id")
);

CREATE TABLE "workout_split" (
  "split" VARCHAR(20) NOT NULL,
  "workout_plan_id" INTEGER NOT NULL,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("split", "workout_plan_id")
);

CREATE TABLE "workout_report" (
  "workout_report_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "workout_plan_id" INTEGER NOT NULL,
  "report_date" DATE NOT NULL,
  "split" VARCHAR(20) NOT NULL,
  PRIMARY KEY ("workout_report_id")
);

CREATE TABLE "split_exercise" (
  "workout_plan_id" INTEGER NOT NULL,
  "split" VARCHAR(20) NOT NULL,
  "exercise_id" INTEGER NOT NULL,
  "execution_order" INTEGER NOT NULL,
  "sets" INTEGER NOT NULL,
  "reps" VARCHAR(10) NOT NULL,
  "advanced_technique" VARCHAR(30),
  "rest_time" INTEGER NOT NULL,
  "active" BOOLEAN DEFAULT true,
  PRIMARY KEY ("workout_plan_id", "split", "exercise_id", "execution_order")
);

CREATE TABLE "set_report" (
  "workout_report_id" INTEGER NOT NULL,
  "exercise_id" INTEGER NOT NULL,
  "split" VARCHAR(20) NOT NULL,
  "workout_plan_id" INTEGER NOT NULL,
  "execution_order" INTEGER NOT NULL,
  "set_number" INTEGER NOT NULL,
  "reps" VARCHAR(20) NOT NULL,
  "weight" INTEGER NOT NULL,
  "notes" VARCHAR(255),
  PRIMARY KEY ("workout_report_id", "exercise_id", "split", "workout_plan_id", "set_number")
);

CREATE UNIQUE INDEX "uq_user_email" ON "user" ("email");
CREATE INDEX "idx_username_user" ON "user" ("username");
CREATE INDEX "idx_email_user" ON "user" ("email");

CREATE UNIQUE INDEX "uq_muscle_group" ON "muscle_group" ("user_id", "group_name");
CREATE INDEX "idx_muscle_group_user_id" ON "muscle_group" ("user_id");

CREATE UNIQUE INDEX "uq_equipment" ON "equipment" ("user_id", "group_name", "equipment_name");
CREATE INDEX "idx_equipment_user_id_group_name" ON "equipment" ("user_id", "group_name");

CREATE UNIQUE INDEX "uq_muscle" ON "muscle" ("user_id", "group_name", "muscle_name");
CREATE INDEX "idx_muscle_user_id_group_name" ON "muscle" ("user_id", "group_name");

CREATE UNIQUE INDEX "uq_exercise" ON "exercise" ("user_id", "exercise_name");
CREATE INDEX "idx_exercise_id" ON "exercise" ("exercise_id");

CREATE INDEX "idx_exercise_id_exercise_muscle" ON "exercise_muscle" ("exercise_id");
CREATE INDEX "idx_muscle_id_exercise_muscle" ON "exercise_muscle" ("muscle_id");

CREATE INDEX "idx_equipment_id_exercise_equipment" ON "exercise_equipment" ("equipment_id");
CREATE INDEX "idx_exercise_id_exercise_equipment" ON "exercise_equipment" ("exercise_id");

CREATE UNIQUE INDEX "uq_workout_plan" ON "workout_plan" ("user_id", "workout_plan_name");
CREATE INDEX "idx_workout_plan_user_id" ON "workout_plan" ("user_id");

CREATE INDEX "idx_workout_plan_id_split_exercise" ON "split_exercise" ("workout_plan_id");
CREATE INDEX "idx_workout_plan_id_workout_report_set_report" ON "set_report" ("workout_plan_id", "workout_report_id");

ALTER TABLE "muscle_group" ADD CONSTRAINT "fk_muscle_group_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "equipment" ADD CONSTRAINT "fk_equipment_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");
ALTER TABLE "equipment" ADD CONSTRAINT "fk_equipment_muscle_group" FOREIGN KEY ("group_name") REFERENCES "muscle_group" ("group_name");

ALTER TABLE "muscle" ADD CONSTRAINT "fk_muscle_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");
ALTER TABLE "muscle" ADD CONSTRAINT "fk_muscle_muscle_group" FOREIGN KEY ("group_name") REFERENCES "muscle_group" ("group_name");

ALTER TABLE "exercise" ADD CONSTRAINT "fk_exercise_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "exercise_muscle" ADD CONSTRAINT "fk_exercise_muscle_muscle" FOREIGN KEY ("muscle_id") REFERENCES "muscle" ("muscle_id");
ALTER TABLE "exercise_muscle" ADD CONSTRAINT "fk_exercise_muscle_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercise" ("exercise_id");

ALTER TABLE "exercise_equipment" ADD CONSTRAINT "fk_exercise_equipment_equipment" FOREIGN KEY ("equipment_id") REFERENCES "equipment" ("equipment_id");
ALTER TABLE "exercise_equipment" ADD CONSTRAINT "fk_exercise_equipment_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercise" ("exercise_id");

ALTER TABLE "workout_plan" ADD CONSTRAINT "fk_workout_plan_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id");

ALTER TABLE "workout_split" ADD CONSTRAINT "fk_workout_split_workout_plan" FOREIGN KEY ("workout_plan_id") REFERENCES "workout_plan" ("workout_plan_id");

ALTER TABLE "workout_report" ADD CONSTRAINT "fk_workout_report_workout_split" FOREIGN KEY ("workout_plan_id", "split") REFERENCES "workout_split" ("workout_plan_id", "split");

ALTER TABLE "split_exercise" ADD CONSTRAINT "fk_split_exercise_workout_split" FOREIGN KEY ("workout_plan_id", "split") REFERENCES "workout_split" ("workout_plan_id", "split");
ALTER TABLE "split_exercise" ADD CONSTRAINT "fk_split_exercise_exercise" FOREIGN KEY ("exercise_id") REFERENCES "exercise" ("exercise_id");

ALTER TABLE "set_report" ADD CONSTRAINT "fk_set_report_split_exercise" FOREIGN KEY ("workout_plan_id", "split", "exercise_id", "execution_order") REFERENCES "split_exercise" ("workout_plan_id", "split", "exercise_id", "execution_order");
ALTER TABLE "set_report" ADD CONSTRAINT "fk_set_report_workout_report" FOREIGN KEY ("workout_report_id") REFERENCES "workout_report" ("workout_report_id");
