services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
      - JWT_SESSION_KEY=${JWT_SESSION_KEY}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - REDIS_URL=${REDIS_URL}

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fittude
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    restart: always
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
secrets:
  db-password:
    file: ./app/database/password.txt
