services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    env_file: 
      - .env

    depends_on:
      fittude-db:
        condition: service_healthy
      fittude-cache:
        condition: service_healthy
  fittude-db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fittude
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  fittude-cache:
    image: redis
    restart: always
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local

