[tool.poetry]
name = "app-treino"
version = "0.1.0"
description = "App para acompanhar a rotina de treinos"
authors = ["Luiz <lcsouzagarcia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kivy = "^2.3.1"
bcrypt = "^4.2.1"
fastapi = {extras = ["standard"], version = "^0.115.6"}
logger = "^1.4"
sqlalchemy = "^2.0.36"
psycopg2-binary = "^2.9.10"


[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.1"
ruff = "^0.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
